- transactiontype: bankfees
- transactiontype: c_auto
- transactiontype: c_donate
- transactiontype: c_entertainment
- transactiontype: c_internet
- transactiontype: c_legalfees
- transactiontype: c_license
- transactiontype: c_mobile
- transactiontype: c_off_exp
- transactiontype: c_parktoll
- transactiontype: c_phone
- transactiontype: c_taxi
- transactiontype: c_travel
- transactiontype: c_website
- transactiontype: carpropertytax
- transactiontype: costbasis
- transactiontype: days
- transactiontype: depreciation
- transactiontype: distribution
- transactiontype: entertainment_personal
- transactiontype: hoa
- transactiontype: ignore
- transactiontype: ignorecorrection
- transactiontype: income
- transactiontype: insurance
- transactiontype: mortgageinterest
- transactiontype: proffees
- transactiontype: renovation
- transactiontype: rent
- transactiontype: repairs
- transactiontype: securitydeposit
- transactiontype: tax
- transactiontype: tenantfees
- transactiontype: utilities
